export const SHOPIFY_MOCK_DATA = {
  store: {
    name: "Debales Store",
    currency: "USD",
    totalProducts: 47,
    totalOrders: 1042,
  },
  products: [
    {
      id: "prod_001",
      name: "Wireless Pro Headphones",
      price: 149.99,
      inventory: 23,
      category: "Electronics",
      sku: "WPH-001",
      status: "active",
    },
    {
      id: "prod_002",
      name: "Smart Watch Series 5",
      price: 299.99,
      inventory: 8,
      category: "Wearables",
      sku: "SWS-005",
      status: "low_stock",
    },
    {
      id: "prod_003",
      name: "Bluetooth Speaker",
      price: 79.99,
      inventory: 45,
      category: "Electronics",
      sku: "BTS-003",
      status: "active",
    },
    {
      id: "prod_004",
      name: "USB-C Hub 7-in-1",
      price: 49.99,
      inventory: 0,
      category: "Accessories",
      sku: "UCH-007",
      status: "out_of_stock",
    },
  ],
  recentOrders: [
    {
      id: "#1042",
      customer: "Emily Davis",
      total: 149.99,
      status: "shipped",
      date: "2024-03-10",
      items: ["Wireless Pro Headphones"],
    },
    {
      id: "#1041",
      customer: "Michael Johnson",
      total: 89.99,
      status: "delivered",
      date: "2024-03-09",
      items: ["Bluetooth Speaker"],
    },
    {
      id: "#1040",
      customer: "Lisa Park",
      total: 349.98,
      status: "processing",
      date: "2024-03-09",
      items: ["Smart Watch Series 5", "USB-C Hub 7-in-1"],
    },
  ],
  revenue: {
    today: 3240.5,
    thisWeek: 18920.75,
    thisMonth: 64500.0,
  },
};

export const CRM_MOCK_DATA = {
  totalCustomers: 284,
  newThisWeek: 12,
  customers: [
    {
      id: "cus_001",
      name: "Sarah Chen",
      company: "TechCorp Inc.",
      email: "sarah@techcorp.com",
      totalSpent: 4200,
      lastOrder: "2024-03-10",
      status: "active",
      tag: "VIP",
    },
    {
      id: "cus_002",
      name: "John Martinez",
      company: "RetailPro",
      email: "john@retailpro.com",
      totalSpent: 1850,
      lastOrder: "2024-02-25",
      status: "at_risk",
      tag: "Follow up",
    },
    {
      id: "cus_003",
      name: "Priya Patel",
      company: "StartupXYZ",
      email: "priya@startupxyz.com",
      totalSpent: 750,
      lastOrder: "2024-03-08",
      status: "active",
      tag: "New",
    },
    {
      id: "cus_004",
      name: "David Kim",
      company: "Kim Enterprises",
      email: "david@kim-ent.com",
      totalSpent: 9600,
      lastOrder: "2024-03-05",
      status: "active",
      tag: "Enterprise",
    },
  ],
  pipeline: {
    leads: 34,
    qualified: 18,
    proposal: 9,
    closing: 4,
    won: 142,
  },
  topDeals: [
    { name: "TechCorp Annual Plan", value: 12000, stage: "proposal" },
    { name: "RetailPro Expansion", value: 8500, stage: "qualified" },
    { name: "Kim Ent. Bulk Order", value: 6000, stage: "closing" },
  ],
};
